validate_ot_nexson.py: ERROR: An ID ("otu1") was repeated in "otu" in "otus(id=otus1)"
