validate_ot_nexson.py: ERROR: An ID ("node0") was repeated in "node in tree(id=tree1)"
validate_ot_nexson.py: ERROR: Disconnected graph found instead of tree including root nodes:"node0", "node0" in "tree(id=tree1)"
