validate_ot_nexson.py: ERROR: An ID ("node0") was repeated in "node in tree(id=tree1)"
